AllCops:
  Exclude:
    - vendor/**/*

Style/MultilineOperationIndentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent
